# Generated by Django 5.0.1 on 2024-01-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='datetime',
            field=models.DateTimeField(default='16/01/2024, 21:08:34'),
        ),
    ]
