# Generated by Django 5.0.1 on 2024-01-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_votes_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='datetime',
            field=models.DateTimeField(default='19/01/2024, 00:12:27'),
        ),
    ]
