# Generated by Django 5.0.1 on 2024-01-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_votes_category_alter_votes_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='datetime',
            field=models.DateTimeField(default='21/01/2024, 01:19:41'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
