# Generated by Django 5.0.1 on 2024-01-21 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_votes_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 12, 18, 35, 913520)),
        ),
    ]
